### ISSUE TITLE
Static Corpus Rewrite

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#10]
Virtual corpus (VC) content can be categorized into static and dynamic. The number of docs of dynamic VC may change over time, while that of static VC must remain the same. To establish static VC, static corpus rewrite adds a restriction "publishDate" with value the date of VC creation, to the virtual corpus query.

**Comment by Akron** [comment]
I think that's not a Kustvakt issue.

**Comment by margaretha** [comment]
Ok. This issue should be handled in Kalamar using indexingDate instead of publishDate.
