### ISSUE TITLE
Reintroduce versioning

### ISSUE THREAD

**Issue by Akron** [KorAP/Kustvakt#25]
At the beginning of Kustvakt development, the Web-API had a version prefix ```/v0.1/```. This was removed without an alternative.
To make breaking API changes possible, versioning should be reintroduced.

There is some discussion ([1](https://twitter.com/fielding/status/376835835670167552), [2](http://blogs.perl.org/users/brian_medley/2014/11/using-minion-with-a-rest-api.html)) whether different ressources is the right way to handle versioning, but I guess it's the easiest for maintenance and for the developer.

This is especially important now that OAuth and plugins should invite external developers to use our API.

**Comment by margaretha** [comment]
API versioning is implemented in f9f8c679bf04f35163de203862922a52ff04d3f1 as URL versioning for both kustvakt full and lite. 

All controllers require "version" as a path segment in the service URLs, except ```api/kustvakt``` controller. Supported versions are listed in ```api/kustvakt/info```.

kustvakt.conf must specify supported api versions. Multiple versions must be separated by an empty space. e.g.

    supported.api.version = v0.1

**Comment by Akron** [comment]
Is this backwards compatible? For example, will a missing version forward to a certain version?

**Comment by Akron** [comment]
Otherwise: Thank you!
