### ISSUE TITLE
Search in unauthorized VC

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#36]
How should access to an authorized VC be handled?
For instance, user A would like to search in a private VC of user B.
Currently, Kustvakt will throw an unauthorized error. 
Should it be more tolerant, e.g. by using rewrite to remove the VC instead?

**Comment by Akron** [comment]
Can you (sorry - again) explain what a private VC in opposite to a public VC? Can a private VC for example be shared with other users?

**Comment by margaretha** [comment]
No problem. 

> Can you (sorry - again) explain what a private VC is in opposite to a public VC? 

A private vc is only be available to the user who creates it.

There are a few types of public vc. System and published vc are available for all users, while project vc are only available to a group of users.

> Can a private VC for example be shared with other users?

Yes, a private vc can be shared by its creator with a group of users, then the type is changed into project.

Besides, a private vc can be shared with all users by publishing it, so the type is changed into published. Even though published vc are available for all users, they are not automatically listed for all. When a logged-in user search for the vc for the first time, after it has been published, the vc is added to the list of available vc to that user.

**Comment by hebasta** [comment]
Am I right with the presumption, that a private vc is not listed for other users? So practically user A would normally not try to  search in a private vc of user B, because he does not easily has knowledge about its existence? Or do I misunderstand something?

**Comment by Akron** [comment]
The normal case where this happens is, when a URL is passed to a collegue.

**Comment by Akron** [comment]
The different VC types seem to be reasonable. I would argue, that the behaviour for referencing a private VC should at least be identical to the behaviour of referencing a shared VC the user is not allowed to access.

In case we decide for a rewrite instead of an error, what the result of the rewrite should be. For example, the reference could be an empty VC - or it could be deleted. I guess, rewriting to an empty VC is more appropriate.

**Comment by margaretha** [comment]
> Am I right with the presumption, that a private vc is not listed for other users?
@hebasta yes

Moreover, users cannot access private vc of other users. Users can only access system, published and their project-vc (the users must be invited to a group and the vc is shared with this group).

**Comment by margaretha** [comment]
> In case we decide for a rewrite instead of an error, what the result of the rewrite should be.

In case there is no other rules in the corpus query, it could be like this:
<pre>
"collection": {
        "rewrites": [{
            "@type": "koral:rewrite",
            "src": "Kustvakt",
            "operation": "operation:deletion",
            "scope": "koral:docGroupRef"
        }]
    }
</pre>

But there is no indication/hint for the deletion. It would nice to have something like status code unauthorized. Such status code may be a good addition for rewrite specification, but it should be discussed in another issue, maybe https://github.com/KorAP/Koral/issues/51.

**Comment by Akron** [comment]
The problem with that rewrite would be, that the user would receive **more** results instead of less. For the moment there is no definition for an empty VC in KoralQuery, but I think that would be a good use case.

**Comment by margaretha** [comment]
@Akron what do you mean with an empty VC? Would it then mean a search on no corpus/data at all?

Since this would not return any result, I suppose an error message (unauthorized access to VC) would be sufficient instead of a rewrite.

**Comment by Akron** [comment]
> Would it then mean a search on no corpus/data at all?

Not in all cases. In case the reference is (somehow nested) in an OR-relation, it would just be ignored.

**Comment by margaretha** [comment]
> Not in all cases. In case the reference is (somehow nested) in an OR-relation, it would just be ignored.

Yes, although I suppose if someone would like to restrict a search in a VC, the query is likely to be an AND-relation. But one may refer to multiple VC, then it would be an OR-relation.

**Comment by Akron** [comment]
Yes. The thing is: A rewrite in that case should restrict more instead of less.

**Comment by margaretha** [comment]
Rewriting into an empty vc is nice but rather more implicit and we still need to add a warning why nonetheless, namely due to unauthorized access to the vc

For the moment, the simple solution of throwing an error with no results is concluded to be sufficient.
