### ISSUE TITLE
Corpus licence with limited number of users

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#41]
Kustvakt should handle the license that limit access to a corpus based on the number of users currently accessing it. e.g Süddeutsche Zeitung, Januar 1995 - Dezember 1999 has QAO-NC-LOC:ids-NU:1 license that limit access to the corpus to only one user at a time.

Solution: default VC rewrite for "all corpora access" should exclude corpora with "NU" keywords in the license.

**Comment by kupietz** [comment]
That's actually a bug in the corpus data that still refers to an outdated license. 
I will fix it there.
