### ISSUE TITLE
Search api returning metadata only 

### ISSUE THREAD

**Issue by Akron** [KorAP/Kustvakt#43]
As described in https://github.com/KorAP/Krill/issues/58:

> Krill should support search queries returning only all metadata without match snippets, thus allowing search on all data without license restrictions.
> 
> Metadata should be return for every match regardless of redundancy.

This requires a change to the rewrite mechanism in Kustvakt as well. Once https://github.com/KorAP/Krill/issues/58 is done, the implementation should follow the descriptions in the then closed Krill issue.

**Comment by margaretha** [comment]
Implemented in 2544cdf9eb295da525f5c6f10fb899ba70ae13a2.

**Comment by Akron** [comment]
This feature should be improved by adding a warning when non-public fields are removed.
