### ISSUE TITLE
Support multiple cq parameters throughout all APIs

### ISSUE THREAD

**Issue by Akron** [KorAP/Kustvakt#46]
Currently a VC is defined by a single ```cq``` parameter throughout multiple endpoints. It would be great to support multiple ```cq``` parameters everywhere to define a single VC with an "and"-conjunction (e.g. ```?cq=pubDate%3D2009-12-06&cq=corpusSigle%3DWPD``` becomes the VC ```pubDate in 2009-12-06 & corpusSigle="WPD"```).

The use case is to rewrite URLs to redirect from a separated instance (like ```/instance/example?...```) to another instance, that incorporates the corpus as a subcorpus by just appending the subcorpus definition as a (potentially additional) ```cq``` parameter (e.g. ```/instance/main?...&cq=exampleCorpus```). By doing that, URLs of separated instances can be published and will keep working, even when the instance is removed, as long as the corpus is transfered to another instance and can be defined as a VC.

**Comment by margaretha** [comment]
Implemented in ed2ee24936f964ca7c9a90539ff9a6f06219bf25.
