### ISSUE TITLE
Confused about authentication

### ISSUE THREAD

**Issue by davidpomerenke** [KorAP/Kustvakt#492]
I want to use the API for searching for newspaper articles that are not under the Creative Commons license, so I want to authenticate. It seems that there are two methods, *Basic HTTP authentication* and *OAuth2* authentication.

I tried it with basic HTTP authentication like this in Python:

```python
requests.get(
    "https://korap.ids-mannheim.de/api/v1.0/search",
    params={...},
    headers={
        "Authorization": (
            "Basic " + str(b64encode(b"email@somewhere.org:iamapassword"))[2:-1]
        ),
    },
```

The result is:

```
{"errors":[[104,"Authentication provider for token type BASIC is not found.","Basic"]]}
```

Thus I tried understanding the other method, OAuth2. I need to obtain an access token, and in order to obtain an access token, I need to specify the `client_id` and client credentials. But in order to register a client, I already need to have an access token? I spent some time trying to figure it out, but unfortunately I remain confused.

Thank you for your help, and for your work more generally! ❤️

**Comment by davidpomerenke** [comment]
I figured it out now.

I can retrieve an access token via the KorAP website, once I am logged in with an account created via COSMAS II. The form for it is a bit hidden, but once found, it is very easy:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/46022183/209333323-e7d7389d-cf52-4a18-8c7a-33e9cb7db133.png">

I think it would be good to mention this somewhere prominently on the wiki @margaretha. 

Before I had known that, I had just assumed that I would need to request the token via the API, and use my email and password as client_id and client_secret, but all of these seem to have been incorrect assumptions. I guess many users of the API will come from science and not from web development, and, like me, will not know what OAuth2 is for, or how it works.

**Comment by kupietz** [comment]
:+1:  yeah, it's an a bit of an easter egg – not quite appropriate for the season. I didn't know that that was the problem, sorry.

There are however more issues about the OAuth2 handling, https://github.com/KorAP/Kalamar/issues/54 or https://github.com/KorAP/RKorAPClient/issues/4, that once solved make it easier.

**Comment by Akron** [comment]
Oh - I misunderstood the problem as well. I added some lines for clarification in the Kustvakt wiki, but making the settings more obvious is an issue for Kalamar (see https://github.com/KorAP/Kalamar/issues/137). I'll close this issue - thank you for the question and sorry, we were too late for answering it.
