### ISSUE TITLE
Support CORS for API request

### ISSUE THREAD

**Issue by Akron** [KorAP/Kustvakt#56]
To simplify API requests in foreign side clients, the API should probably support [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Before implementing, the security issues should be reviewed.

This feature was requested by F. Michaelis.

**Comment by Akron** [comment]
I added CORS headers in Gerrit #3771 .

**Comment by Akron** [comment]
I guess this can be closed as we don't plan to open the API without proxy anymore.

**Comment by margaretha** [comment]
Thanks for handling this.
