### ISSUE TITLE
Endpoint for requesting basic information about the currently logged in user

### ISSUE THREAD

**Issue by notesjor** [KorAP/Kustvakt#566]
I would like to retrieve the profile-data of the currently logged in user - (e.g. username). The user has previously logged in via OAuth2 to a client app I created. Unfortunately, since the login runs via OAuth2, I don't even see the user name in the sign-in process. However, this is necessary, for example, to retrieve a list of virtual corpora.

**Comment by margaretha** [comment]
Added a wiki page: https://github.com/KorAP/Kustvakt/wiki/User-Info
