### ISSUE TITLE
Missing scope documentation vc_info 

### ISSUE THREAD

**Issue by notesjor** [KorAP/Kustvakt#567]
The scope vc_info is not documented on page [OAuth2-Authorization-Code](https://github.com/KorAP/Kustvakt/wiki/Service:-OAuth2-Authorization-Code). Please insert.

**Comment by margaretha** [comment]
Added.

**Comment by margaretha** [comment]
I have added `vc_info` to the authorization request wiki page and created a new page listing the scopes: https://github.com/KorAP/Kustvakt/wiki/OAuth2-Authorization-Scope

Only stable scopes are listed, that have been tested and are freely used by clients. 

`edit_vc` is still unstable and may still change in the future.

The responses of VC info and VC list web-service are also not fixed yet and may change in the near future.
