### ISSUE TITLE
Searching time API requests vs. via Kalamar

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#577]
@notesjor reported that direct API requests sometimes takes much longer for searching that query via Kalamar.
Could you please posted an example? I cannot find any big time differences.

**Comment by margaretha** [comment]
Kalamar stores "the number of results" thus perform search with option "cutoff=true" that improves the searching time. See https://github.com/KorAP/Kustvakt/wiki/Service:-Search-GET 

We have implemented a cache for this in Kustvakt as well. See https://github.com/KorAP/Kustvakt/commit/5a5b9958126fede1c20d7645eac23a27c8ff8a88

**Comment by notesjor** [comment]
Dear Eliza, thank you very much - I'll take a look at it next week.
