### ISSUE TITLE
/User-Info - scope error!

### ISSUE THREAD

**Issue by notesjor** [KorAP/Kustvakt#614]
I want to use https://github.com/KorAP/Kustvakt/wiki/User-Info

To do this, I need to register a OAuth2-Token with the USER_INFO scope.

There are serveral problems:
- The registration fails - USER_INFO is not registred as a valid scope. I get the following Response-URL: /api/oauth2/korap?error_description=USER_INFO+is+an+invalid+scope
- I also tried USER-INFO, user-info and user_info - no success
- The name USER_INFO is inconsitend because all other scopes are lowercase and a underscore is used e.g. match_info, vc_info

**Comment by margaretha** [comment]
Hi Jan, the user info web-service is currently only available on the test instance. The scope is case-insensitive, but you are right `user_info` in lower case is better for consistency. I have updated the wiki page. Sorry for the inconvenience.

**Comment by notesjor** [comment]
works fine - thanks!
