### ISSUE TITLE
/meta/totalResults in the API search response should remain a number

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kustvakt#668]
but now returns a string: 

```shell
 $ GET 'https://korap.ids-mannheim.de/instance/test/api/v1.0/search?q=Ameisenplage&ql=poliqarp' | json_pp | grep totalResults
```
```
      "totalResults" : "13",
```

**Comment by notesjor** [comment]
Ja, aber die Rückgabe eines einzelnen numerischen Werts kann Probleme bereiten. Gerade dann, wenn man die Rückgabe als JSON parst - was beim Rest der Rückgaben der KorapAPI der Fall ist. Ich würde das nicht ändern.

**Comment by kupietz** [comment]
> Ja, aber die Rückgabe eines einzelnen numerischen Werts kann Probleme bereiten. Gerade dann, wenn man die Rückgabe als JSON parst - was beim Rest der Rückgaben der KorapAPI der Fall ist. Ich würde das nicht ändern.

Ja, es geht genau darum, dass sich gegenüber der Version, die aktuell im Produktionsbetrieb ist, nichts ändert.
