### ISSUE TITLE
Open API documentation

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#744]
Use Open API / Swagger for API examples

**Comment by notesjor** [comment]
Brauchst Du evtl. eine Vorlage? - Ich habe bereits ein paar Dinge per OpenAPI/Swagger dokumentiert (für den Eigengebrauch) - müsste daher noch erweitert werden.

**Comment by margaretha** [comment]
Ja gerne. Ich habe bisher nur die Spezifikation für Search API geschrieben. Sorry dass ich erst heute antwortet, inzwischen haben wir andere Dinge zu tun. :-)

**Comment by margaretha** [comment]
KorAP openapi documentation is now available at https://korap.ids-mannheim.de/api/v1.0/openapi/

The documentation only includes stable APIs.
