### ISSUE TITLE
 annoying default option "availability eq CC-BY.*"

### ISSUE THREAD

**Issue by notesjor** [KorAP/Kustvakt#756]
If you set up your own Docker container with your own body material, the "availability eq CC-BY.*" filter is always set. Even if you explicitly delete it - after a query has been executed, the filter is active again. This means that it is essential to set the “availability” property for your own corpora, as otherwise you cannot use your own corpora.

**Comment by margaretha** [comment]
It turns out that the port number for kalamar in the compose.yaml: 64543 has been unused in Windows, so it should use another port.

**Comment by margaretha** [comment]
The behavior comes from CollectionRewrite. Kustvakt full version includes CollectionRewrite by default. It can be customized in the spring configuration.

If any rewrite and authentication is not necessary, the lite version is more suitable. Please consider using the lite version.
