### ISSUE TITLE
Remove corpusQuery param in statistics web-service

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kustvakt#758]
`corpusQuery` param in the [statistics web-service](https://github.com/KorAP/Kustvakt/wiki/Service:-Virtual-Corpus-Statistics) has been deprecated with notification for years. Can we remove it safely?

**Comment by Akron** [comment]
Yes, it can be removed safely. Kalamar sends both `cq` and `corpusQuery` for quite some time now. I proposed a change to remove `corpusQuery` completely.
