### ISSUE TITLE
OAuth2 - Wrong Signin Redirect

### ISSUE THREAD

**Issue by notesjor** [KorAP/Kustvakt#773]
The following error is critical - I ask for quick response. The function has already worked - it is already in use in several productive applications.

For some time now, the previous OAuth2 authentication has no longer worked. 

The following used to work:
1. an OAuth2 application APP was created by user DEV.
2. when user USER was asked to register for the APP, this user was shown the login screen (user / password) and could then confirm access to the APP application.

Now:
1. still works.
2. if the USER now gets the login screen and signs in, he does NOT get the confirmation prompt for APP-access - but: the normal KorAP search is displayed. When the window is reloaded, the user is also offered to register a new application (normal users don't register APPs).

Therefore: Something in the routing seems to be wrong.

**Comment by margaretha** [comment]
Hi Jan, sorry it took a while to response. There is no new changes in the API regarding the OAuth2 authorization flow. I have just checked the authorization flow using my client and cannot reproduce the issue. Did you get any error message?

**Comment by notesjor** [comment]
![09-10-2024_11-35-27](https://github.com/user-attachments/assets/3b7b4267-6eb9-4b39-96fe-a9382c59ac5f)
The error has not yet been fixed in the current KorAP instance.
However, the “Client not found” error no longer appears.
But you still don't get to the page with the accesses, you're forwarded directly to the KorAP search. This means that OAuth2 still does not work from my side (as before).

**Comment by margaretha** [comment]
Yes, please check on https://korap.ids-mannheim.de/instance/test. If it is fine, I will deploy it on the main instance.

**Comment by notesjor** [comment]
Ah ok, that explains it. Thank you. I can't test it to 100% - but it seems to work.

**Comment by margaretha** [comment]
The main instance has been updated with the hot fix.

**Comment by notesjor** [comment]
tested - works again as expected - thanks alot 👍
